before:
  hooks:
    - go mod tidy
    
release:
  draft: true
  prerelease: auto
  
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      
    goarch:
      - amd64
      - arm64

archives:
- format: zip
  id: reconbot
  replacements:
      darwin: Darwin
      
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
