name: 🌥 Docker Push

on:
  workflow_run:
    workflows: ["🎉 Release Binary"]
    types:
      - completed
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Get Github tag
        id: meta
        run: |
          echo "::set-output name=tag::$(curl --silent "https://api.github.com/repos/w3security/reconbot/releases/latest" | jq -r .tag_name)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: w3security
          password: dckr_pat_B00nqDPJ1b_dv0B2Q6VE7b2abC4

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: w3security/reconbot:latest,w3security/reconbot:${{ steps.meta.outputs.tag }}
